// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    databaseURL: 'https://food-ordering-app-e30fd-default-rtdb.firebaseio.com/',

    apiKey: 'AIzaSyAb8gmUT9-1VCoO4BBCs-HaYBylPyvcCoQ',
    appId: '1:363409048783:web:0ef6562ca478ca3914e3ba',
    messagingSenderId: '363409048783',
    projectId: 'food-ordering-app-e30fd',
    authDomain: 'food-ordering-app-e30fd.firebaseapp.com',
    storageBucket: 'food-ordering-app-e30fd.appspot.com',
    measurementId: 'G-K4P3XFEMVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkTBQeKjXEN3uXp12jCGINHCT5FEqMgaE',
    appId: '1:363409048783:android:44b914f84f61d8fd14e3ba',
    messagingSenderId: '363409048783',
    projectId: 'food-ordering-app-e30fd',
    storageBucket: 'food-ordering-app-e30fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG2AqJAuPhQ1uJiQa2I-O-krkr-xy8MN8',
    appId: '1:363409048783:ios:1b0ec4749455946d14e3ba',
    messagingSenderId: '363409048783',
    projectId: 'food-ordering-app-e30fd',
    storageBucket: 'food-ordering-app-e30fd.appspot.com',
    iosClientId: '363409048783-lnmt8u0hhs21h7bm4mt5u2iohjpiur9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG2AqJAuPhQ1uJiQa2I-O-krkr-xy8MN8',
    appId: '1:363409048783:ios:1b0ec4749455946d14e3ba',
    messagingSenderId: '363409048783',
    projectId: 'food-ordering-app-e30fd',
    storageBucket: 'food-ordering-app-e30fd.appspot.com',
    iosClientId: '363409048783-lnmt8u0hhs21h7bm4mt5u2iohjpiur9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderingApp',
  );
}
