// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsamClwu1Wnizf97ltLkOMAVtv3mLC8QU',
    appId: '1:1072924263093:web:d3449fed98bee6f5bab4fc',
    messagingSenderId: '1072924263093',
    projectId: 'food-ordering-app-bab62',
    authDomain: 'food-ordering-app-bab62.firebaseapp.com',
    storageBucket: 'food-ordering-app-bab62.appspot.com',
    measurementId: 'G-C4YBS4GG9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6KTow6UM_WIeIzdf-_jtzLJMVfPlO8yA',
    appId: '1:1072924263093:android:71300f49679c1b31bab4fc',
    messagingSenderId: '1072924263093',
    projectId: 'food-ordering-app-bab62',
    storageBucket: 'food-ordering-app-bab62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT1fs63ySJAHrdL-BYa3JAjf6catetMhE',
    appId: '1:1072924263093:ios:a1a390056b3ea64dbab4fc',
    messagingSenderId: '1072924263093',
    projectId: 'food-ordering-app-bab62',
    storageBucket: 'food-ordering-app-bab62.appspot.com',
    iosClientId: '1072924263093-8od8nclqm7v84000qfqun5kdqr2iju20.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT1fs63ySJAHrdL-BYa3JAjf6catetMhE',
    appId: '1:1072924263093:ios:a1a390056b3ea64dbab4fc',
    messagingSenderId: '1072924263093',
    projectId: 'food-ordering-app-bab62',
    storageBucket: 'food-ordering-app-bab62.appspot.com',
    iosClientId: '1072924263093-8od8nclqm7v84000qfqun5kdqr2iju20.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderingApp',
  );
}
